name: pointcept-dev
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.0
  - torchvision=0.20.0
  - torchaudio=2.5.0
  - ninja
  - h5py
  - pyyaml
  - tensorboard
  - tensorboardx
  - wandb
  - yapf
  - addict
  - einops
  - scipy
  - plyfile
  - termcolor
  - timm
  - ftfy
  - regex
  - tqdm
  - matplotlib
  - black
  - open3d
  - pip:
      - torch-cluster
      - torch-scatter
      - torch-sparse
      - torch-geometric
      - git+https://github.com/octree-nn/ocnn-pytorch.git
      - git+https://github.com/openai/CLIP.git
      #- git+https://github.com/Dao-AILab/flash-attention.git
      - ./libs/pointops
      - ./libs/pointgroup_ops
